import { Category } from "@/types"

export const mockCategories: Category[] = [
  {
    id: "cat_teknologi",
    name: "Teknologi",
    slug: "teknologi",
    description: "Semua hal tentang teknologi, gadget, dan software.",
    coverImage: null,
    parentId: null,
    parent: null,
    children: [],
    postCount: 15,
    order: 1,
    isVisible: true,
    seo: { metaTitle: null, metaDescription: null, canonicalUrl: null },
    color: "#3b82f6",
    icon: "laptop",
    createdAt: new Date("2023-01-01"),
    updatedAt: new Date("2026-06-01"),
  },
  {
    id: "cat_bisnis",
    name: "Bisnis",
    slug: "bisnis",
    description: "Berita dan strategi bisnis terkini.",
    coverImage: null,
    parentId: null,
    parent: null,
    children: [],
    postCount: 8,
    order: 2,
    isVisible: true,
    seo: { metaTitle: null, metaDescription: null, canonicalUrl: null },
    color: "#10b981",
    icon: "briefcase",
    createdAt: new Date("2023-01-05"),
    updatedAt: new Date("2026-06-01"),
  },
  {
    id: "cat_gaya_hidup",
    name: "Gaya Hidup",
    slug: "gaya-hidup",
    description: "Tips gaya hidup, kesehatan, dan hobi.",
    coverImage: null,
    parentId: null,
    parent: null,
    children: [],
    postCount: 12,
    order: 3,
    isVisible: true,
    seo: { metaTitle: null, metaDescription: null, canonicalUrl: null },
    color: "#f43f5e",
    icon: "coffee",
    createdAt: new Date("2023-01-10"),
    updatedAt: new Date("2026-06-01"),
  },
  {
    id: "cat_programming",
    name: "Programming",
    slug: "programming",
    description: "Tutorial dan tips programming.",
    coverImage: null,
    parentId: "cat_teknologi",
    parent: null,
    children: [],
    postCount: 10,
    order: 1,
    isVisible: true,
    seo: { metaTitle: null, metaDescription: null, canonicalUrl: null },
    color: "#6366f1",
    icon: "code",
    createdAt: new Date("2023-02-01"),
    updatedAt: new Date("2026-06-01"),
  },
  {
    id: "cat_ai_ml",
    name: "AI & Machine Learning",
    slug: "ai-machine-learning",
    description: "Perkembangan AI terbaru.",
    coverImage: null,
    parentId: "cat_teknologi",
    parent: null,
    children: [],
    postCount: 5,
    order: 2,
    isVisible: true,
    seo: { metaTitle: null, metaDescription: null, canonicalUrl: null },
    color: "#8b5cf6",
    icon: "bot",
    createdAt: new Date("2023-03-01"),
    updatedAt: new Date("2026-06-01"),
  },
]
